services:
  streamlit:
    build: .
    container_name: online-retail-streamlit
    ports:
      - "8502:8501"
    volumes:
      - ./app
      - ./models:/app/models

  jupyter:
    build: .
    container_name: online-retail-jupyter
    ports:
      - "8889:8888"
    volumes:
      - .:/app
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root    